// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: risk-control.proto

package riskcontrol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RiskControlServer_LoginAuth_FullMethodName          = "/riskcontrol.RiskControlServer/LoginAuth"
	RiskControlServer_WithDrawAuth_FullMethodName       = "/riskcontrol.RiskControlServer/WithDrawAuth"
	RiskControlServer_ChangePasswdNotify_FullMethodName = "/riskcontrol.RiskControlServer/ChangePasswdNotify"
	RiskControlServer_DeviceInfo_FullMethodName         = "/riskcontrol.RiskControlServer/DeviceInfo"
)

// RiskControlServerClient is the client API for RiskControlServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskControlServerClient interface {
	LoginAuth(ctx context.Context, in *LoginAuthRequest, opts ...grpc.CallOption) (*LoginAuthResponse, error)
	WithDrawAuth(ctx context.Context, in *WithdrawAuthRequest, opts ...grpc.CallOption) (*WithdrawAuthResponse, error)
	ChangePasswdNotify(ctx context.Context, in *ChangePasswdNotifyRequest, opts ...grpc.CallOption) (*ChangePasswdNotifyResponse, error)
	DeviceInfo(ctx context.Context, in *DeviceInfoRequest, opts ...grpc.CallOption) (*DeviceInfoResponse, error)
}

type riskControlServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskControlServerClient(cc grpc.ClientConnInterface) RiskControlServerClient {
	return &riskControlServerClient{cc}
}

func (c *riskControlServerClient) LoginAuth(ctx context.Context, in *LoginAuthRequest, opts ...grpc.CallOption) (*LoginAuthResponse, error) {
	out := new(LoginAuthResponse)
	err := c.cc.Invoke(ctx, RiskControlServer_LoginAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControlServerClient) WithDrawAuth(ctx context.Context, in *WithdrawAuthRequest, opts ...grpc.CallOption) (*WithdrawAuthResponse, error) {
	out := new(WithdrawAuthResponse)
	err := c.cc.Invoke(ctx, RiskControlServer_WithDrawAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControlServerClient) ChangePasswdNotify(ctx context.Context, in *ChangePasswdNotifyRequest, opts ...grpc.CallOption) (*ChangePasswdNotifyResponse, error) {
	out := new(ChangePasswdNotifyResponse)
	err := c.cc.Invoke(ctx, RiskControlServer_ChangePasswdNotify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskControlServerClient) DeviceInfo(ctx context.Context, in *DeviceInfoRequest, opts ...grpc.CallOption) (*DeviceInfoResponse, error) {
	out := new(DeviceInfoResponse)
	err := c.cc.Invoke(ctx, RiskControlServer_DeviceInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskControlServerServer is the server API for RiskControlServer service.
// All implementations must embed UnimplementedRiskControlServerServer
// for forward compatibility
type RiskControlServerServer interface {
	LoginAuth(context.Context, *LoginAuthRequest) (*LoginAuthResponse, error)
	WithDrawAuth(context.Context, *WithdrawAuthRequest) (*WithdrawAuthResponse, error)
	ChangePasswdNotify(context.Context, *ChangePasswdNotifyRequest) (*ChangePasswdNotifyResponse, error)
	DeviceInfo(context.Context, *DeviceInfoRequest) (*DeviceInfoResponse, error)
	mustEmbedUnimplementedRiskControlServerServer()
}

// UnimplementedRiskControlServerServer must be embedded to have forward compatible implementations.
type UnimplementedRiskControlServerServer struct {
}

func (UnimplementedRiskControlServerServer) LoginAuth(context.Context, *LoginAuthRequest) (*LoginAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAuth not implemented")
}
func (UnimplementedRiskControlServerServer) WithDrawAuth(context.Context, *WithdrawAuthRequest) (*WithdrawAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithDrawAuth not implemented")
}
func (UnimplementedRiskControlServerServer) ChangePasswdNotify(context.Context, *ChangePasswdNotifyRequest) (*ChangePasswdNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePasswdNotify not implemented")
}
func (UnimplementedRiskControlServerServer) DeviceInfo(context.Context, *DeviceInfoRequest) (*DeviceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceInfo not implemented")
}
func (UnimplementedRiskControlServerServer) mustEmbedUnimplementedRiskControlServerServer() {}

// UnsafeRiskControlServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskControlServerServer will
// result in compilation errors.
type UnsafeRiskControlServerServer interface {
	mustEmbedUnimplementedRiskControlServerServer()
}

func RegisterRiskControlServerServer(s grpc.ServiceRegistrar, srv RiskControlServerServer) {
	s.RegisterService(&RiskControlServer_ServiceDesc, srv)
}

func _RiskControlServer_LoginAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControlServerServer).LoginAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControlServer_LoginAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControlServerServer).LoginAuth(ctx, req.(*LoginAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControlServer_WithDrawAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControlServerServer).WithDrawAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControlServer_WithDrawAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControlServerServer).WithDrawAuth(ctx, req.(*WithdrawAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControlServer_ChangePasswdNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswdNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControlServerServer).ChangePasswdNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControlServer_ChangePasswdNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControlServerServer).ChangePasswdNotify(ctx, req.(*ChangePasswdNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskControlServer_DeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskControlServerServer).DeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskControlServer_DeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskControlServerServer).DeviceInfo(ctx, req.(*DeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskControlServer_ServiceDesc is the grpc.ServiceDesc for RiskControlServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskControlServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "riskcontrol.RiskControlServer",
	HandlerType: (*RiskControlServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginAuth",
			Handler:    _RiskControlServer_LoginAuth_Handler,
		},
		{
			MethodName: "WithDrawAuth",
			Handler:    _RiskControlServer_WithDrawAuth_Handler,
		},
		{
			MethodName: "ChangePasswdNotify",
			Handler:    _RiskControlServer_ChangePasswdNotify_Handler,
		},
		{
			MethodName: "DeviceInfo",
			Handler:    _RiskControlServer_DeviceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "risk-control.proto",
}
