// proto 语法版本 proto3

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: logic-bridge.proto

// proto 包名

package logic_bridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AICheckLogicBridge_CheckEvidence_FullMethodName = "/logic_bridge.AICheckLogicBridge/checkEvidence"
	AICheckLogicBridge_CheckReason_FullMethodName   = "/logic_bridge.AICheckLogicBridge/checkReason"
	AICheckLogicBridge_Health_FullMethodName        = "/logic_bridge.AICheckLogicBridge/health"
)

// AICheckLogicBridgeClient is the client API for AICheckLogicBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AICheckLogicBridgeClient interface {
	// 主要业务接口, 支持批量提交submission进行校验
	CheckEvidence(ctx context.Context, in *AIEvidenceCheckReq, opts ...grpc.CallOption) (*AIEvidenceCheckResp, error)
	CheckReason(ctx context.Context, in *AIReasonCheckReq, opts ...grpc.CallOption) (*AIReasonCheckResp, error)
	// 用于 k8s 健康检查
	Health(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error)
}

type aICheckLogicBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewAICheckLogicBridgeClient(cc grpc.ClientConnInterface) AICheckLogicBridgeClient {
	return &aICheckLogicBridgeClient{cc}
}

func (c *aICheckLogicBridgeClient) CheckEvidence(ctx context.Context, in *AIEvidenceCheckReq, opts ...grpc.CallOption) (*AIEvidenceCheckResp, error) {
	out := new(AIEvidenceCheckResp)
	err := c.cc.Invoke(ctx, AICheckLogicBridge_CheckEvidence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aICheckLogicBridgeClient) CheckReason(ctx context.Context, in *AIReasonCheckReq, opts ...grpc.CallOption) (*AIReasonCheckResp, error) {
	out := new(AIReasonCheckResp)
	err := c.cc.Invoke(ctx, AICheckLogicBridge_CheckReason_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aICheckLogicBridgeClient) Health(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error) {
	out := new(HealthCheckResp)
	err := c.cc.Invoke(ctx, AICheckLogicBridge_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AICheckLogicBridgeServer is the server API for AICheckLogicBridge service.
// All implementations must embed UnimplementedAICheckLogicBridgeServer
// for forward compatibility
type AICheckLogicBridgeServer interface {
	// 主要业务接口, 支持批量提交submission进行校验
	CheckEvidence(context.Context, *AIEvidenceCheckReq) (*AIEvidenceCheckResp, error)
	CheckReason(context.Context, *AIReasonCheckReq) (*AIReasonCheckResp, error)
	// 用于 k8s 健康检查
	Health(context.Context, *HealthCheckReq) (*HealthCheckResp, error)
	mustEmbedUnimplementedAICheckLogicBridgeServer()
}

// UnimplementedAICheckLogicBridgeServer must be embedded to have forward compatible implementations.
type UnimplementedAICheckLogicBridgeServer struct {
}

func (UnimplementedAICheckLogicBridgeServer) CheckEvidence(context.Context, *AIEvidenceCheckReq) (*AIEvidenceCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEvidence not implemented")
}
func (UnimplementedAICheckLogicBridgeServer) CheckReason(context.Context, *AIReasonCheckReq) (*AIReasonCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckReason not implemented")
}
func (UnimplementedAICheckLogicBridgeServer) Health(context.Context, *HealthCheckReq) (*HealthCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAICheckLogicBridgeServer) mustEmbedUnimplementedAICheckLogicBridgeServer() {}

// UnsafeAICheckLogicBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AICheckLogicBridgeServer will
// result in compilation errors.
type UnsafeAICheckLogicBridgeServer interface {
	mustEmbedUnimplementedAICheckLogicBridgeServer()
}

func RegisterAICheckLogicBridgeServer(s grpc.ServiceRegistrar, srv AICheckLogicBridgeServer) {
	s.RegisterService(&AICheckLogicBridge_ServiceDesc, srv)
}

func _AICheckLogicBridge_CheckEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIEvidenceCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AICheckLogicBridgeServer).CheckEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AICheckLogicBridge_CheckEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AICheckLogicBridgeServer).CheckEvidence(ctx, req.(*AIEvidenceCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AICheckLogicBridge_CheckReason_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIReasonCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AICheckLogicBridgeServer).CheckReason(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AICheckLogicBridge_CheckReason_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AICheckLogicBridgeServer).CheckReason(ctx, req.(*AIReasonCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AICheckLogicBridge_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AICheckLogicBridgeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AICheckLogicBridge_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AICheckLogicBridgeServer).Health(ctx, req.(*HealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AICheckLogicBridge_ServiceDesc is the grpc.ServiceDesc for AICheckLogicBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AICheckLogicBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logic_bridge.AICheckLogicBridge",
	HandlerType: (*AICheckLogicBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkEvidence",
			Handler:    _AICheckLogicBridge_CheckEvidence_Handler,
		},
		{
			MethodName: "checkReason",
			Handler:    _AICheckLogicBridge_CheckReason_Handler,
		},
		{
			MethodName: "health",
			Handler:    _AICheckLogicBridge_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic-bridge.proto",
}
