// proto 语法版本 proto3

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: evidence-checker.proto

// proto 包名

package evidence_checker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EvidenceCheck_CheckEvidence_FullMethodName      = "/evidence_checker.EvidenceCheck/checkEvidence"
	EvidenceCheck_Health_FullMethodName             = "/evidence_checker.EvidenceCheck/health"
	EvidenceCheck_CheckImageRepeated_FullMethodName = "/evidence_checker.EvidenceCheck/checkImageRepeated"
	EvidenceCheck_CheckImageInfo_FullMethodName     = "/evidence_checker.EvidenceCheck/checkImageInfo"
	EvidenceCheck_CheckImageEdited_FullMethodName   = "/evidence_checker.EvidenceCheck/checkImageEdited"
	EvidenceCheck_CheckWebpageInfo_FullMethodName   = "/evidence_checker.EvidenceCheck/checkWebpageInfo"
)

// EvidenceCheckClient is the client API for EvidenceCheck service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EvidenceCheckClient interface {
	// 主要业务接口, 支持批量提交submission进行校验
	CheckEvidence(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error)
	// 用于 k8s 健康检查
	Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// 单独的检测接口, 可以不使用
	CheckImageRepeated(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error)
	// 单独的图片校验接口, 可以不使用
	CheckImageInfo(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error)
	// 单独的伪图片检测接口, 可以不使用
	CheckImageEdited(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error)
	// 单独的webpage校验接口, 可以不使用
	CheckWebpageInfo(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error)
}

type evidenceCheckClient struct {
	cc grpc.ClientConnInterface
}

func NewEvidenceCheckClient(cc grpc.ClientConnInterface) EvidenceCheckClient {
	return &evidenceCheckClient{cc}
}

func (c *evidenceCheckClient) CheckEvidence(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error) {
	out := new(EvidenceCheckResp)
	err := c.cc.Invoke(ctx, EvidenceCheck_CheckEvidence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evidenceCheckClient) Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, EvidenceCheck_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evidenceCheckClient) CheckImageRepeated(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error) {
	out := new(EvidenceCheckResp)
	err := c.cc.Invoke(ctx, EvidenceCheck_CheckImageRepeated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evidenceCheckClient) CheckImageInfo(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error) {
	out := new(EvidenceCheckResp)
	err := c.cc.Invoke(ctx, EvidenceCheck_CheckImageInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evidenceCheckClient) CheckImageEdited(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error) {
	out := new(EvidenceCheckResp)
	err := c.cc.Invoke(ctx, EvidenceCheck_CheckImageEdited_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evidenceCheckClient) CheckWebpageInfo(ctx context.Context, in *EvidenceCheckReq, opts ...grpc.CallOption) (*EvidenceCheckResp, error) {
	out := new(EvidenceCheckResp)
	err := c.cc.Invoke(ctx, EvidenceCheck_CheckWebpageInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvidenceCheckServer is the server API for EvidenceCheck service.
// All implementations must embed UnimplementedEvidenceCheckServer
// for forward compatibility
type EvidenceCheckServer interface {
	// 主要业务接口, 支持批量提交submission进行校验
	CheckEvidence(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error)
	// 用于 k8s 健康检查
	Health(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// 单独的检测接口, 可以不使用
	CheckImageRepeated(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error)
	// 单独的图片校验接口, 可以不使用
	CheckImageInfo(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error)
	// 单独的伪图片检测接口, 可以不使用
	CheckImageEdited(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error)
	// 单独的webpage校验接口, 可以不使用
	CheckWebpageInfo(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error)
	mustEmbedUnimplementedEvidenceCheckServer()
}

// UnimplementedEvidenceCheckServer must be embedded to have forward compatible implementations.
type UnimplementedEvidenceCheckServer struct {
}

func (UnimplementedEvidenceCheckServer) CheckEvidence(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEvidence not implemented")
}
func (UnimplementedEvidenceCheckServer) Health(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedEvidenceCheckServer) CheckImageRepeated(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckImageRepeated not implemented")
}
func (UnimplementedEvidenceCheckServer) CheckImageInfo(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckImageInfo not implemented")
}
func (UnimplementedEvidenceCheckServer) CheckImageEdited(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckImageEdited not implemented")
}
func (UnimplementedEvidenceCheckServer) CheckWebpageInfo(context.Context, *EvidenceCheckReq) (*EvidenceCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckWebpageInfo not implemented")
}
func (UnimplementedEvidenceCheckServer) mustEmbedUnimplementedEvidenceCheckServer() {}

// UnsafeEvidenceCheckServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvidenceCheckServer will
// result in compilation errors.
type UnsafeEvidenceCheckServer interface {
	mustEmbedUnimplementedEvidenceCheckServer()
}

func RegisterEvidenceCheckServer(s grpc.ServiceRegistrar, srv EvidenceCheckServer) {
	s.RegisterService(&EvidenceCheck_ServiceDesc, srv)
}

func _EvidenceCheck_CheckEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceCheckServer).CheckEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceCheck_CheckEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceCheckServer).CheckEvidence(ctx, req.(*EvidenceCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvidenceCheck_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceCheckServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceCheck_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceCheckServer).Health(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvidenceCheck_CheckImageRepeated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceCheckServer).CheckImageRepeated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceCheck_CheckImageRepeated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceCheckServer).CheckImageRepeated(ctx, req.(*EvidenceCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvidenceCheck_CheckImageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceCheckServer).CheckImageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceCheck_CheckImageInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceCheckServer).CheckImageInfo(ctx, req.(*EvidenceCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvidenceCheck_CheckImageEdited_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceCheckServer).CheckImageEdited(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceCheck_CheckImageEdited_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceCheckServer).CheckImageEdited(ctx, req.(*EvidenceCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EvidenceCheck_CheckWebpageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceCheckServer).CheckWebpageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceCheck_CheckWebpageInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceCheckServer).CheckWebpageInfo(ctx, req.(*EvidenceCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EvidenceCheck_ServiceDesc is the grpc.ServiceDesc for EvidenceCheck service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvidenceCheck_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evidence_checker.EvidenceCheck",
	HandlerType: (*EvidenceCheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkEvidence",
			Handler:    _EvidenceCheck_CheckEvidence_Handler,
		},
		{
			MethodName: "health",
			Handler:    _EvidenceCheck_Health_Handler,
		},
		{
			MethodName: "checkImageRepeated",
			Handler:    _EvidenceCheck_CheckImageRepeated_Handler,
		},
		{
			MethodName: "checkImageInfo",
			Handler:    _EvidenceCheck_CheckImageInfo_Handler,
		},
		{
			MethodName: "checkImageEdited",
			Handler:    _EvidenceCheck_CheckImageEdited_Handler,
		},
		{
			MethodName: "checkWebpageInfo",
			Handler:    _EvidenceCheck_CheckWebpageInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evidence-checker.proto",
}
