early.captchaType:math
#spring.data.mongodb.host=<EXTERNAL_IP_REDACTED>
spring.data.mongodb.host=<INTERNAL_IP_REDACTED>
#<EXTERNAL_IP_REDACTED>
spring.data.mongodb.port=27017
spring.data.mongodb.database=annotation
#spring.data.mongodb.username=root
#spring.data.mongodb.password=<REDACTED>
# 国际化资源文件路径
spring.messages.basename=i18n/messages/messages
# Redis服务器连接端口
spring.redis.port=6379
# Redis服务器地址
spring.redis.host=<INTERNAL_IP_REDACTED>
# Redis数据库索引（默认为0）
#spring.redis.database=0
# Redis服务器连接密码（默认为空）
spring.redis.password=
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1ms
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-idle=8
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=0
# 连接超时时间（毫秒）
spring.redis.timeout=5000ms
# Swagger配置
# 是否开启swagger
swagger.enabled=true
# 请求前缀
swagger.pathMapping=/
server.port=9093
server.host=http://<INTERNAL_IP_REDACTED>:9093
resources_path=/home/www/qiangzhibei/resources/
filterScriptPath=cd /home/www/qiangzhibei/resources/wsi.annotation && sh filter.sh
dockerFilterAppPath=/home/www/qiangzhibei/resources/
score.host=http://<INTERNAL_IP_REDACTED>:5000
token.header=Authorization
token.secret=abcdefghijklmnopqrstuvwxyz
token.expireTime=360
oss.ali.endpoint=http://oss-cn-hangzhou.aliyuncs.com
oss.ali.accessKeyId=PnIpbSSmgmdZvQYn
oss.ali.accessKeySecret=c6oyRN8AsY5RXMkNstXszQRRKiSvc8
oss.ali.bucket=publicdoc
oss.ali.visit.url=https://publicdoc.oss-cn-hangzhou.aliyuncs.com/
spring.resources.static-locations=file:${resources_path}
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
voice.result.docker-url=/opt/data
voice.result.real-url=/home/www/qiangzhibei/DOCKER_TEST/opt/data

project.iipsrvUrl: http://<INTERNAL_IP_REDACTED>:8083/fcgi-bin/iipsrv.fcgi
project.serverURL: http://<INTERNAL_IP_REDACTED>:9090
project.maxCropSize: 15000
project.tiffinfo: tiffinfo
project.vips: /usr/local/bin/vips

codatta.login.url=https://app.test.b18a.io/api/user/login
cookie.header=Codatta-Medical-WSI-Token
token.saveTime=10080

