# Handler for Starlark code snippet generation and validation
"""
Handles the generation and validation of Starlark code snippets for data validation.

This module provides the `StarlarkHandler` class, which encapsulates the logic
for creating Starlark functions (e.g., `validate_data(data)`) from natural
language descriptions (using an LLM) and validating data by executing these
functions using Python's `exec`. A Starlark-like `type()` function is injected
into the execution scope to handle type comparisons as expected in Starlark.

Warning: Executing code generated by LLMs can be risky. While Starlark itself
is sandboxed, using Python's `exec` to run it bypasses some of those
sandboxing benefits if not carefully managed. Always review generated code.
"""

import json
import traceback
import io
import contextlib
from typing import Dict, Optional, Any, List, Union

# Assuming llm_interface.py is in the same directory or src is in PYTHONPATH
from ..llm_interface import LLMInterface # Relative import might be problematic
from . import prompt_config # Import shared prompt configurations

class StarlarkHandler:
    """
    Manages Starlark code snippet generation and execution for validation.
    - generate: Generates Starlark code using an LLM based on a natural language description and optional examples.
    - validate: Validates given JSON data by executing the provided Starlark code snippet using Python's exec (with type-mimic support).
    """
    def __init__(self, llm_client: LLMInterface):
        """
        Initializes the StarlarkHandler.

        Args:
            llm_client: An instance conforming to the LLMInterface protocol,
                        used for LLM-dependent generation operations.
        """
        if not (hasattr(llm_client, 'generate_response') and callable(llm_client.generate_response) and
                hasattr(llm_client, 'model_name')):
            raise TypeError("llm_client must be an instance that adheres to the LLMInterface protocol.")
        self.llm_client = llm_client

    @staticmethod
    def _starlark_type_mimic(obj):
        if isinstance(obj, str):
            return "string"
        if isinstance(obj, bool): # Must come before int, as bool is a subclass of int
            return "bool"
        if isinstance(obj, int):
            return "int"
        if isinstance(obj, list):
            return "list"
        if isinstance(obj, dict):
            return "dict"
        if obj is None:
            return "NoneType"
        # Fallback for other types (e.g., float, custom objects if they were to appear)
        # Starlark's type() for functions, structs, etc., is more specific.
        # This basic mimic covers common JSON-derived types.
        return type(obj).__name__

    def generate(
        self,
        description: str,
        example_data_list: Optional[List[Dict[str, Any]]] = None,
        basic_artifact_content: Optional[Union[Dict[str, Any], str]] = None,
        basic_artifact_type: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate Starlark code for validation based on a natural language description and examples.
        Returns a dictionary including 'success', 'artifact' (the Starlark code string),
        'needs_further_ai_validation' (boolean), and 'error'.
        """
        try:
            system_prompt = self._get_starlark_system_prompt()
            user_prompt = self._get_starlark_user_prompt(description, example_data_list)
            
            # Request JSON output from LLM
            raw_response = self.llm_client.generate_response(system_prompt, user_prompt, json_mode=True)
            
            if raw_response.error:
                return {
                    "success": False, 
                    "artifact": None, 
                    "needs_further_ai_validation": True, # Default to needing AI on error
                    "error": f"LLM client error: {raw_response.error}"
                }
            if not raw_response.content:
                return {
                    "success": False, 
                    "artifact": None, 
                    "needs_further_ai_validation": True, 
                    "error": "LLM returned no content."
                }

            try:
                llm_output = json.loads(raw_response.content)
                starlark_code = llm_output.get("starlark_code")
                needs_further_ai_validation = llm_output.get("needs_further_ai_validation", True) # Default to True if missing

                if not isinstance(starlark_code, str) or not starlark_code.strip():
                    return {
                        "success": False, 
                        "artifact": None, 
                        "needs_further_ai_validation": True, 
                        "error": "LLM output missing 'starlark_code' or it's empty."
                    }
                if not isinstance(needs_further_ai_validation, bool):
                    # Log a warning or handle as an error, for now, default to True
                    needs_further_ai_validation = True 
                    # Consider adding a specific error or warning if this is critical

            except json.JSONDecodeError as e:
                return {
                    "success": False, 
                    "artifact": None, 
                    "needs_further_ai_validation": True, 
                    "error": f"Failed to parse LLM JSON response: {e}. Response: {raw_response.content[:500]}"
                }
            except AttributeError as e: # Handles cases where llm_output might not be a dict
                 return {
                    "success": False, 
                    "artifact": None, 
                    "needs_further_ai_validation": True, 
                    "error": f"Invalid LLM JSON structure: {e}. Response: {raw_response.content[:500]}"
                }

        except Exception as e:
            # Use _handle_generation_error or a more specific error structure
            # For now, returning a generic error structure consistent with the new return type
            return {
                "success": False, 
                "artifact": None, 
                "needs_further_ai_validation": True,
                "error": f"StarlarkHandler.generate exception: {type(e).__name__} - {e}"
            }
        
        return {
            "success": True, 
            "artifact": starlark_code.strip(), 
            "needs_further_ai_validation": needs_further_ai_validation,
            "error": None
        }

    def validate(
        self,
        json_data: Any,
        starlark_code_artifact: str # Starlark code is a string
    ) -> Dict[str, Any]:
        """
        Validates data using the provided Starlark code snippet.
        Returns a dictionary with 'success' (data validity), 'validation_type', 'message', and 'details'.
        WARNING: Executes LLM-generated code. Starlark is sandboxed, but caution is advised.
        Note: This uses Python's `exec`. For true Starlark execution, a Starlark interpreter library would be needed.
        The `json_data` (Python dict/list) is passed as is. Starlark's `type()` behaves differently than Python's.
        The example Starlark code uses `type(data.get('key')) == 'string'`, which is a Starlark way to check types.
        """
        local_scope = {}
        stdout_capture = io.StringIO()
        try:
            print("\n--- WARNING: Executing LLM-generated Starlark code (via Python's exec). ---")
            print("Ensure the code's origin and content are trusted. Starlark has sandboxing, but `exec` is Python's.")

            # Strip markdown fences
            code_lines = starlark_code_artifact.strip().splitlines()
            if len(code_lines) >= 2:
                if code_lines[0].startswith("```python") and code_lines[-1] == "```":
                    starlark_code_artifact = "\n".join(code_lines[1:-1])
                elif code_lines[0] == "```" and code_lines[-1] == "```": # For generic ``` ``` blocks
                    starlark_code_artifact = "\n".join(code_lines[1:-1])
            
            print(f"Code to be executed (after stripping fences):\n{starlark_code_artifact[:500]}{'...' if len(starlark_code_artifact) > 500 else ''}\n---")
            
            # For Starlark executed via Python's exec, we might need to provide
            # a basic `struct` and `dict` if the code expects them in a specific Starlark way.
            # However, the example uses .get() which works on Python dicts.
            # If Starlark-specific globals are needed, they'd be added to `starlark_globals`.
            starlark_globals = globals().copy() 
            # Add any specific Starlark builtins or functions if necessary for the generated code
            # For example, if `struct` or `fail` are used: 
            # class StructMock(dict): pass # A very basic mock
            # def fail_mock(msg): raise Exception(msg)
            # starlark_globals['struct'] = StructMock 
            # starlark_globals['fail'] = fail_mock
            starlark_globals['type'] = StarlarkHandler._starlark_type_mimic # Inject our type mimic

            with contextlib.redirect_stdout(stdout_capture):
                exec(starlark_code_artifact, starlark_globals, local_scope)
            
            if 'validate_data' not in local_scope or not callable(local_scope['validate_data']):
                return {
                    "success": False, 
                    "validation_type": "starlark", 
                    "message": "The Starlark code must define a callable function named 'validate_data'.", 
                    "details": ["'validate_data' function not found or not callable in the executed Starlark code."]
                    }
            
            validation_func = local_scope['validate_data']
            # Pass json_data directly. The Starlark code should handle it as a Python dict/list.
            result = validation_func(json_data) 

            if not isinstance(result, dict) or 'success' not in result or 'details' not in result:
                return {
                    "success": False, 
                    "validation_type": "starlark", 
                    "message": "Starlark function 'validate_data' did not return the expected dictionary format.", 
                    "details": [f"Expected {{'success': bool, 'details': list_or_string}}, got: {str(result)[:200]}"]
                    }
            
            is_valid = result.get('success', False)
            starlark_details = result.get('details', 'No details provided by Starlark script.')

            if not isinstance(is_valid, bool):
                # Prepend error to details if is_valid is not a boolean
                error_msg = f"Script returned non-boolean for 'success' (value: {is_valid})."
                if isinstance(starlark_details, list):
                    starlark_details.insert(0, error_msg)
                else:
                    starlark_details = [error_msg, str(starlark_details)]
                is_valid = False
            
            # Ensure details is a list of strings
            if isinstance(starlark_details, str):
                final_details = [starlark_details]
            elif isinstance(starlark_details, list):
                final_details = [str(item) for item in starlark_details] # Ensure all items are strings
            else:
                final_details = [f"Unexpected details format from Starlark: {str(starlark_details)[:200]}"]

            return {
                "success": is_valid, 
                "validation_type": "starlark", 
                "message": "Starlark validation successful." if is_valid else "Starlark validation failed.", 
                "details": final_details
                }

        except Exception as e:
            captured_stdout = stdout_capture.getvalue()
            error_message = f"Error executing Starlark validation code: {type(e).__name__} - {e}."
            detailed_error_info = f"Traceback:\n{traceback.format_exc()}\nCaptured Stdout:\n{captured_stdout}"
            return {
                "success": False, 
                "validation_type": "starlark", 
                "message": error_message, 
                "details": [detailed_error_info]
                }
        finally:
            stdout_capture.close()

    @staticmethod
    def _get_starlark_system_prompt() -> str:
        return (
            "You are an expert AI assistant that generates Starlark validation code and assesses its comprehensiveness. "
            "Your goal is to create Starlark code that supports a 'Platform Auditor' AI in validating data for a system that collects high-quality labeled data for training specialized AI models.\n\n"
            f"**{prompt_config.PLATFORM_CONTEXT.strip()}**\n\n"
            f"**{prompt_config.PLATFORM_AUDITOR_ROLE_DESCRIPTION.strip()}**\n\n"
            f"**{prompt_config.DEFAULT_DATA_QUALITY_CRITERIA_INTRO.strip()}**\n"
            f"{prompt_config.DEFAULT_DATA_QUALITY_CRITERIA_LIST}\n"
            f"**{prompt_config.USER_RULES_PRIORITY_STATEMENT.strip()}**\n\n"
            f"**Starlark Implementation Notes Regarding General Quality Criteria:**\n"
            f"{prompt_config.STARLARK_IMPLEMENTATION_NOTES}\n\n"
            "**Your Task:**\n"
            "1.  Generate a Starlark function `validate_data(data)` based on the user's natural language description and examples. This function must return a dictionary: `{\"success\": True/False, \"details\": \"validation message\"}`.\n"
            "2.  Incorporate the user's EXPLICIT rules. These are paramount.\n"
            "3.  Where appropriate and not conflicting with user rules, try to implement the general quality criteria (listed above) in your Starlark code, following the Starlark Implementation Notes. Use `fail('message')` for violations.\n"
            "4.  Critically assess if your Starlark code ALONE can validate ALL aspects from the user's description AND relevant general quality criteria that Starlark *can* handle (refer to Starlark Implementation Notes).\n\n"
            "**Output Format (JSON ONLY):**\n"
            "{\n"
            "  \"starlark_code\": \"def validate_data(data):\\n    # Starlark-compatible Python code. Use data.get('key') for safety.\\n    # Example: if not data.get('my_field','').strip(): fail('my_field cannot be empty')\\n    # Example: if len(data.get('description','')) < 5: fail('description too short')\\n    # Example: if not re.match(r'[^@]+@[^@]+\\.[^@]+', data.get('email','')): fail('invalid email format')\\n    return {'success': True, 'details': 'Validation successful'}\",\n"
            "  \"needs_further_ai_validation\": <boolean>\n"
            "}\n\n"
            f"**Guidance for 'needs_further_ai_validation' flag:**\n"
            f"{prompt_config.NEEDS_FURTHER_AI_VALIDATION_GUIDANCE}\n\n"
            "Do NOT include any other text, explanations, or markdown formatting outside this JSON object.\n"
            "Ensure the \"starlark_code\" is a valid Starlark function string (properly escaped for JSON) and the overall output is a single JSON object."
        )

    def _get_starlark_user_prompt(self, description: str, example_data_list: Optional[List[Dict[str, Any]]] = None) -> str:
        """
        Formats the user prompt for the LLM using the description and example data.
        """
        user_prompt_parts = [f"Natural language description for Starlark validation:\n{description}"]
        if example_data_list:
            user_prompt_parts.append("\nHere are some example data instances that the Starlark code should handle correctly:")
            for i, example_data in enumerate(example_data_list):
                try:
                    example_str = json.dumps(example_data, indent=2, ensure_ascii=False)
                    user_prompt_parts.append(f"\nExample {i+1}:\n```json\n{example_str}\n```")
                except Exception as e:
                    user_prompt_parts.append(f"\nExample {i+1}: [Error serializing example data: {e}]")
        return "\n".join(user_prompt_parts)
