
mongodb_url = "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.4"
database = "risk-control"
loginBlockCategory = ["7200-5","86400-10"]
withdrawBlockCategory = 86400


